//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Oasis.Lib
{
    public partial class ContentSidebarContent
    {
        #region Primitive Properties
    
        public virtual int ContentSidebarContentId
        {
            get;
            set;
        }
    
        public virtual int ContentId
        {
            get { return _contentId; }
            set
            {
                if (_contentId != value)
                {
                    if (Content != null && Content.ContentId != value)
                    {
                        Content = null;
                    }
                    _contentId = value;
                }
            }
        }
        private int _contentId;
    
        public virtual int SidebarContentId
        {
            get { return _sidebarContentId; }
            set
            {
                if (_sidebarContentId != value)
                {
                    if (SidebarContent != null && SidebarContent.SidebarContentId != value)
                    {
                        SidebarContent = null;
                    }
                    _sidebarContentId = value;
                }
            }
        }
        private int _sidebarContentId;

        #endregion
        #region Navigation Properties
    
        public virtual Content Content
        {
            get { return _content; }
            set
            {
                if (!ReferenceEquals(_content, value))
                {
                    var previousValue = _content;
                    _content = value;
                    FixupContent(previousValue);
                }
            }
        }
        private Content _content;
    
        public virtual SidebarContent SidebarContent
        {
            get { return _sidebarContent; }
            set
            {
                if (!ReferenceEquals(_sidebarContent, value))
                {
                    var previousValue = _sidebarContent;
                    _sidebarContent = value;
                    FixupSidebarContent(previousValue);
                }
            }
        }
        private SidebarContent _sidebarContent;

        #endregion
        #region Association Fixup
    
        private void FixupContent(Content previousValue)
        {
            if (previousValue != null && previousValue.ContentSidebarContents.Contains(this))
            {
                previousValue.ContentSidebarContents.Remove(this);
            }
    
            if (Content != null)
            {
                if (!Content.ContentSidebarContents.Contains(this))
                {
                    Content.ContentSidebarContents.Add(this);
                }
                if (ContentId != Content.ContentId)
                {
                    ContentId = Content.ContentId;
                }
            }
        }
    
        private void FixupSidebarContent(SidebarContent previousValue)
        {
            if (previousValue != null && previousValue.ContentSidebarContents.Contains(this))
            {
                previousValue.ContentSidebarContents.Remove(this);
            }
    
            if (SidebarContent != null)
            {
                if (!SidebarContent.ContentSidebarContents.Contains(this))
                {
                    SidebarContent.ContentSidebarContents.Add(this);
                }
                if (SidebarContentId != SidebarContent.SidebarContentId)
                {
                    SidebarContentId = SidebarContent.SidebarContentId;
                }
            }
        }

        #endregion
    }
}
