//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Oasis.Lib
{
    public partial class EventStatu
    {
        #region Primitive Properties
    
        public virtual int EventStatusId
        {
            get;
            set;
        }
    
        public virtual string EventStatusName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Event> Events
        {
            get
            {
                if (_events == null)
                {
                    var newCollection = new FixupCollection<Event>();
                    newCollection.CollectionChanged += FixupEvents;
                    _events = newCollection;
                }
                return _events;
            }
            set
            {
                if (!ReferenceEquals(_events, value))
                {
                    var previousValue = _events as FixupCollection<Event>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupEvents;
                    }
                    _events = value;
                    var newValue = value as FixupCollection<Event>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupEvents;
                    }
                }
            }
        }
        private ICollection<Event> _events;

        #endregion
        #region Association Fixup
    
        private void FixupEvents(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Event item in e.NewItems)
                {
                    item.EventStatu = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Event item in e.OldItems)
                {
                    if (ReferenceEquals(item.EventStatu, this))
                    {
                        item.EventStatu = null;
                    }
                }
            }
        }

        #endregion
    }
}
