//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Oasis.Lib
{
    public partial class Group
    {
        #region Primitive Properties
    
        public virtual int GroupId
        {
            get;
            set;
        }
    
        public virtual string GroupName
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<UserGroup> UserGroups
        {
            get
            {
                if (_userGroups == null)
                {
                    var newCollection = new FixupCollection<UserGroup>();
                    newCollection.CollectionChanged += FixupUserGroups;
                    _userGroups = newCollection;
                }
                return _userGroups;
            }
            set
            {
                if (!ReferenceEquals(_userGroups, value))
                {
                    var previousValue = _userGroups as FixupCollection<UserGroup>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUserGroups;
                    }
                    _userGroups = value;
                    var newValue = value as FixupCollection<UserGroup>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUserGroups;
                    }
                }
            }
        }
        private ICollection<UserGroup> _userGroups;

        #endregion
        #region Association Fixup
    
        private void FixupUserGroups(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (UserGroup item in e.NewItems)
                {
                    item.Group = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (UserGroup item in e.OldItems)
                {
                    if (ReferenceEquals(item.Group, this))
                    {
                        item.Group = null;
                    }
                }
            }
        }

        #endregion
    }
}
