//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Oasis.Lib
{
    public partial class OasisEntities : ObjectContext
    {
        public const string ConnectionString = "name=OasisEntities";
        public const string ContainerName = "OasisEntities";
    
        #region Constructors
    
        public OasisEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public OasisEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public OasisEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Page> Pages
        {
            get { return _pages  ?? (_pages = CreateObjectSet<Page>("Pages")); }
        }
        private ObjectSet<Page> _pages;
    
        public ObjectSet<Post> Posts
        {
            get { return _posts  ?? (_posts = CreateObjectSet<Post>("Posts")); }
        }
        private ObjectSet<Post> _posts;
    
        public ObjectSet<Demographic> Demographics
        {
            get { return _demographics  ?? (_demographics = CreateObjectSet<Demographic>("Demographics")); }
        }
        private ObjectSet<Demographic> _demographics;
    
        public ObjectSet<Event> Events
        {
            get { return _events  ?? (_events = CreateObjectSet<Event>("Events")); }
        }
        private ObjectSet<Event> _events;
    
        public ObjectSet<EventRegistration> EventRegistrations
        {
            get { return _eventRegistrations  ?? (_eventRegistrations = CreateObjectSet<EventRegistration>("EventRegistrations")); }
        }
        private ObjectSet<EventRegistration> _eventRegistrations;
    
        public ObjectSet<EventType> EventTypes
        {
            get { return _eventTypes  ?? (_eventTypes = CreateObjectSet<EventType>("EventTypes")); }
        }
        private ObjectSet<EventType> _eventTypes;
    
        public ObjectSet<Payment> Payments
        {
            get { return _payments  ?? (_payments = CreateObjectSet<Payment>("Payments")); }
        }
        private ObjectSet<Payment> _payments;
    
        public ObjectSet<ProBillRate> ProBillRates
        {
            get { return _proBillRates  ?? (_proBillRates = CreateObjectSet<ProBillRate>("ProBillRates")); }
        }
        private ObjectSet<ProBillRate> _proBillRates;
    
        public ObjectSet<Rank> Ranks
        {
            get { return _ranks  ?? (_ranks = CreateObjectSet<Rank>("Ranks")); }
        }
        private ObjectSet<Rank> _ranks;
    
        public ObjectSet<Transaction> Transactions
        {
            get { return _transactions  ?? (_transactions = CreateObjectSet<Transaction>("Transactions")); }
        }
        private ObjectSet<Transaction> _transactions;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<UserAccess> UserAccesses
        {
            get { return _userAccesses  ?? (_userAccesses = CreateObjectSet<UserAccess>("UserAccesses")); }
        }
        private ObjectSet<UserAccess> _userAccesses;
    
        public ObjectSet<UserBilling> UserBillings
        {
            get { return _userBillings  ?? (_userBillings = CreateObjectSet<UserBilling>("UserBillings")); }
        }
        private ObjectSet<UserBilling> _userBillings;
    
        public ObjectSet<UserStatu> UserStatus
        {
            get { return _userStatus  ?? (_userStatus = CreateObjectSet<UserStatu>("UserStatus")); }
        }
        private ObjectSet<UserStatu> _userStatus;
    
        public ObjectSet<UserType> UserTypes
        {
            get { return _userTypes  ?? (_userTypes = CreateObjectSet<UserType>("UserTypes")); }
        }
        private ObjectSet<UserType> _userTypes;
    
        public ObjectSet<EventStatu> EventStatus
        {
            get { return _eventStatus  ?? (_eventStatus = CreateObjectSet<EventStatu>("EventStatus")); }
        }
        private ObjectSet<EventStatu> _eventStatus;
    
        public ObjectSet<Content> Contents
        {
            get { return _contents  ?? (_contents = CreateObjectSet<Content>("Contents")); }
        }
        private ObjectSet<Content> _contents;
    
        public ObjectSet<ContentSidebarContent> ContentSidebarContents
        {
            get { return _contentSidebarContents  ?? (_contentSidebarContents = CreateObjectSet<ContentSidebarContent>("ContentSidebarContents")); }
        }
        private ObjectSet<ContentSidebarContent> _contentSidebarContents;
    
        public ObjectSet<SidebarContent> SidebarContents
        {
            get { return _sidebarContents  ?? (_sidebarContents = CreateObjectSet<SidebarContent>("SidebarContents")); }
        }
        private ObjectSet<SidebarContent> _sidebarContents;
    
        public ObjectSet<Group> Groups
        {
            get { return _groups  ?? (_groups = CreateObjectSet<Group>("Groups")); }
        }
        private ObjectSet<Group> _groups;
    
        public ObjectSet<UserGroup> UserGroups
        {
            get { return _userGroups  ?? (_userGroups = CreateObjectSet<UserGroup>("UserGroups")); }
        }
        private ObjectSet<UserGroup> _userGroups;
    
        public ObjectSet<CommunityActivity> CommunityActivities
        {
            get { return _communityActivities  ?? (_communityActivities = CreateObjectSet<CommunityActivity>("CommunityActivities")); }
        }
        private ObjectSet<CommunityActivity> _communityActivities;

        #endregion
    }
}
