//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Oasis.Lib
{
    public partial class Payment
    {
        #region Primitive Properties
    
        public virtual int PaymentId
        {
            get;
            set;
        }
    
        public virtual decimal Amount
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual string FromFirstName
        {
            get;
            set;
        }
    
        public virtual string FromLastName
        {
            get;
            set;
        }
    
        public virtual string Address1
        {
            get;
            set;
        }
    
        public virtual string Address2
        {
            get;
            set;
        }
    
        public virtual string City
        {
            get;
            set;
        }
    
        public virtual string State
        {
            get;
            set;
        }
    
        public virtual string ZipCode
        {
            get;
            set;
        }
    
        public virtual string CCNumber
        {
            get;
            set;
        }
    
        public virtual string CCType
        {
            get;
            set;
        }
    
        public virtual string CCExpMonth
        {
            get;
            set;
        }
    
        public virtual string CCExpYear
        {
            get;
            set;
        }
    
        public virtual System.DateTime PaymentDate
        {
            get;
            set;
        }
    
        public virtual string Status
        {
            get;
            set;
        }
    
        public virtual string StatusDescription
        {
            get;
            set;
        }

        #endregion
    }
}
