//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Oasis.Lib
{
    public partial class UserGroup
    {
        #region Primitive Properties
    
        public virtual int UserGroupId
        {
            get;
            set;
        }
    
        public virtual int UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (User != null && User.UserId != value)
                    {
                        User = null;
                    }
                    _userId = value;
                }
            }
        }
        private int _userId;
    
        public virtual int GroupId
        {
            get { return _groupId; }
            set
            {
                if (_groupId != value)
                {
                    if (Group != null && Group.GroupId != value)
                    {
                        Group = null;
                    }
                    _groupId = value;
                }
            }
        }
        private int _groupId;

        #endregion
        #region Navigation Properties
    
        public virtual Group Group
        {
            get { return _group; }
            set
            {
                if (!ReferenceEquals(_group, value))
                {
                    var previousValue = _group;
                    _group = value;
                    FixupGroup(previousValue);
                }
            }
        }
        private Group _group;
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion
        #region Association Fixup
    
        private void FixupGroup(Group previousValue)
        {
            if (previousValue != null && previousValue.UserGroups.Contains(this))
            {
                previousValue.UserGroups.Remove(this);
            }
    
            if (Group != null)
            {
                if (!Group.UserGroups.Contains(this))
                {
                    Group.UserGroups.Add(this);
                }
                if (GroupId != Group.GroupId)
                {
                    GroupId = Group.GroupId;
                }
            }
        }
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.UserGroups.Contains(this))
            {
                previousValue.UserGroups.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.UserGroups.Contains(this))
                {
                    User.UserGroups.Add(this);
                }
                if (UserId != User.UserId)
                {
                    UserId = User.UserId;
                }
            }
        }

        #endregion
    }
}
